server:
  port: 8000

#密码加密传输，前端公钥加密，后端私钥解密 rsa.private_key
rsa:
  private_key: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAukO+T4uFHh0a+aZTl/UtToo9GmLb0sWbkTRxiFZKkeihi1nl/GIEv147lwbeyjnCHVxL1H5xbLrNf8lspo+h6QIDAQABAkA3APQ9Fy1LNDsYB9bdo8gqTkY2+YSCnFoRKhRwt1Kz/SZBOg9Mswrqq1X92y7DemkhiOPb4CF+ncAoZh8ICw/lAiEA5Rt99hqkHNI9m9CWhUZeEwyjnJV5iNZVqM+mXx2Om+sCIQDQINuZcMVU98XHe5svzHbCjP9bLC7Ig1tbjjQf2oooewIhAJXpllNp/UbKnvuM0mEkuTvXwlscR6ktLmHGdgO48G6/AiBvDJkfTeR8aZfF0FYFMvtK4yB87R4pLq1YNI/rTxfYcQIgBx6hbiPqBtBocdzQoFjNrNsLEJUv2qiV4T2H9nPEoSM=

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eladmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

