server:
  port: 8000

#密码加密传输，前端公钥加密，后端私钥解密 rsa.private_key
rsa:
  public_key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALpDvk+LhR4dGvmmU5f1LU6KPRpi29LFm5E0cYhWSpHooYtZ5fxiBL9eO5cG3so5wh1cS9R+cWy6zX/JbKaPoekCAwEAAQ==
  private_key: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAukO+T4uFHh0a+aZTl/UtToo9GmLb0sWbkTRxiFZKkeihi1nl/GIEv147lwbeyjnCHVxL1H5xbLrNf8lspo+h6QIDAQABAkA3APQ9Fy1LNDsYB9bdo8gqTkY2+YSCnFoRKhRwt1Kz/SZBOg9Mswrqq1X92y7DemkhiOPb4CF+ncAoZh8ICw/lAiEA5Rt99hqkHNI9m9CWhUZeEwyjnJV5iNZVqM+mXx2Om+sCIQDQINuZcMVU98XHe5svzHbCjP9bLC7Ig1tbjjQf2oooewIhAJXpllNp/UbKnvuM0mEkuTvXwlscR6ktLmHGdgO48G6/AiBvDJkfTeR8aZfF0FYFMvtK4yB87R4pLq1YNI/rTxfYcQIgBx6hbiPqBtBocdzQoFjNrNsLEJUv2qiV4T2H9nPEoSM=

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eladmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

#配置actuator开放的接口
management:
  endpoints:
    web:
      exposure:
        include: "*"

